### ISSUE TITLE
Вопрос по проекту

### ISSUE THREAD

**Issue by Yourun-proger** [Hrafnir/stp_flask_3#2]
А что ты собственно делаешь в этом проекте? Что-то там про ивенты?

**Comment by hraffiest** [comment]
Дак это чисто учебный проект) я уж и не помню, элементарное аги с jsonify)

**Comment by Yourun-proger** [comment]
@hraffiest , я вижу, как ты хардкодишь дамп моделей в дикт , поэтому советую попробовать мою либу - https://github.com/Yourun-proger/kefir . Только форк не делай! Версия ещё сырая) Но звездой можешь поддержать)
